apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dcloud-app-user-1"
  labels:
    app: "dcloud-app-user-1"
spec:
  selector:
    matchLabels:
      app: "dcloud-app-user-1"
  replicas: 1
  template:
    metadata:
      labels:
        app: "dcloud-app-user-1"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "bastion:latest"
          ports:
            - name: "ssh"
              containerPort: 2222
            - name: "http"
              containerPort: 9000
          name: "dcloud-app-user-1"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: SUDO_ACCESS
              value: "true"
            - name: PASSWORD_ACCESS
              value: "true"
            - name: USER_NAME
              value: "admin"
            - name: USER_PASSWORD
              value: "admin"
            - name: PUBLIC_KEY
              value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCppqFXAbgYpA7k3d8s62CNFyRIKUtqkipuaquv1Pl4EGIlwKz+0RaenaGAJi96FyjhwtxXTUS3RhsaxXHaUkNmv1iV81v+0VMICImAv+Eo2k68qUh8Dmh2dslXXIO/5Te6LDaIxIKFrjMCLdcE9vrkfpmCgB6P0DzWn79bHh4h9u51PlzU8ilnJ3i5wGSdMLHd23eXvDeJ2RI0vLl+3oxMBOVKZLFkWvovukT9isdQ4XeyWBVYoih3WD+0QJaWozwLsn0bBSbIL0YmOUf/Zq1+AQ6/ic23m5A7qbVMVgskQGTXFo9BmJ4sjHrhR4aWhR089gYqy2rwqYdMdr3AgBjFxbjaQ8dOBielivLAMUUcLRqzw7SJtzzLhQ+Kl83vlLmooa/HS2kfIQB6caCp3uQbcwKQuGX3Ufwi2QWFWYfAYlImr5oz09vPyqy1s7MafPgTB8F+stEa8llfWZ5T0itzEqstnm6yvx7sYyXdZ21DzAd+5tFTBAzOsW0U3blL0C8= dkuzkin@demandbase.com"
