#/bin/bash

kubectl apply -f deployment/kubernetes/dcloud/bastion/autogenerated/

nohup kubectl port-forward svc/dcloud-bastion-$1 2222 >port-forward-2222.log 2>&1 &

echo $! >port-forward-2222.pid

nohup ssh -p 2222 -N -R 18080:localhost:8080 admin@localhost >ssh-1.log 2>&1 &

echo $! >ssh-1.pid

nohup kubect port-forward svc/dcloud-bastion-$1 8080:8081 >port-forward-2223.log 3>&1 &

echo $! >port-forward-2223.pid

sleep 60

kill $(cat port-forward-2222.pid) $(cat port-forward-2223.pid) $(cat ssh-1.pid)

rm port-forward-2222.pid port-forward-2223.pid ssh-1.pid
