apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bastion-ingress-proxy"
  labels:
    app: "bastion-ingress-proxy"
spec:
  selector:
    matchLabels:
      app: "bastion-ingress-proxy"
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: "bastion-ingress-proxy"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "bastion-ingress-proxy"
          ports:
            - name: "http"
              hostPort: 8080
              containerPort: 80
          name: "bastion-ingress-proxy"
