apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dcloud-proxy"
  labels:
    app: "dcloud-proxy"
spec:
  selector:
    matchLabels:
      app: "dcloud-proxy"
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: "dcloud-proxy"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "dcloud-proxy"
          ports:
            - name: "http"
              containerPort: 8080
          name: "dcloud-proxy"
          env:
            - name: PORT
              value: "8080"

