apiVersion: v1
kind: Service
metadata:
  name: dcloud-app-user-2
spec:
  selector:
    app: dcloud-app-user-2
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
