apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dcloud-app-user-2"
  labels:
    app: "dcloud-app-user-2"
spec:
  selector:
    matchLabels:
      app: "dcloud-app-user-2"
  replicas: 1
  template:
    metadata:
      labels:
        app: "dcloud-app-user-2"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "bastion:latest"
          ports:
            - name: "ssh"
              containerPort: 2222
            - name: "http"
              containerPort: 8080
          name: "dcloud-app-user-2"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: SUDO_ACCESS
              value: "true"
            - name: PASSWORD_ACCESS
              value: "true"
            - name: USER_NAME
              value: "admin"
            - name: USER_PASSWORD
              value: "admin"
            - name: PUBLIC_KEY
              value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJMAAy/ULxD22/VgewpqBvcv1ooZzutEI/0pQc3NWIvWfG7mXOUYY2I6GwYchFaHOOKQ97E24OlXEFNssDDQBGw2eju+T3R7jfFu1sACWroThkYSInKTh4i8w5J7o6VGxSKXvVG8PZwTKiAUxX6xtj5HhWE/tZS9407riCFs7LlTciEAAfwcD6w3uzc1reu54fVEsgagHjLCivJNmqJUnJ+VSqMHtdoN95zzvJkDf4o5PWLn4AUZEj4Kqz2SE7/NPgBWPMBaGTogQuVMzQDcu/DlWiJEZpGCeFoCba8PXIrP4zeh7prwNlwwVlqy2nvTGjWEfWWaxpr9K41OzatfSvNl1AcIhY3VpID7Y/EA+07QSyZgn7x0DMzdXuiELN6CQVUv8FPzHrspwsxajIKDuI87596gIJitYU/xo4aExyVmbVubDo+VyRpHI8c4ajX73tXqWHDruXboeTIw04GGzNu1PkgNoCuOhTE91niWSHJYk7CU4hQVpjfastaB5AKZVBIqU9ONjzrKvGl2aJoDul+wDnmZGh+wXpYhNZ+od1qtufgHoDZDSHAxwkWPS29daH55lhe3v4Kwl544JtuYs91T3u1S9BrVw/beGf0YPcZNrLtcarzkeYYJRyGtiz6OWpa5ZOEj9EdQjfOb5DsDIVT3LgzGUGdGPS98dwDrcUHQ== vvasyliev@MBP-H0X964TX7J"
