apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "a"
  labels:
    app: "a"
spec:
  selector:
    matchLabels:
      app: "a"
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: "a"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "a"
          ports:
            - name: "http"
              containerPort: 8080
          name: "a"
          env:
            - name: PORT
              value: "8080"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: "RollingUpdate"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "a"
  labels:
    app: "a"
spec:
  selector:
    app: "a"
  ports:
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
      appProtocol: http
  sessionAffinity: "None"
  type: "ClusterIP"
