#!/usr/bin/env bash

kubectl apply -f deployment/kubernetes/dcloud/bastion/autogenerated/

function cleanup {
    echo "Cleaning up fork processes..."
    kill $(jobs -p) &>/dev/null
}

trap cleanup INT

kubectl port-forward svc/dcloud-bastion-egress-$1 2222 &
ssh -p 2222 -N -R 8080:localhost:18080 admin@localhost &
kubectl port-forward svc/dcloud-bastion-ingress-$1 8080:80 &

echo "Dcloud started, press ctrl+c to quite"
wait %1 %2 %3

cleanup
