#!/usr/bin/env bash

kubectl apply -f deployment/kubernetes/dcloud/bastion/autogenerated/

nohup kubectl port-forward svc/dcloud-bastion-egress-$1 2222 >/tmp/port-forward-2222.log 2>&1 &

echo $! >/tmp/port-forward-2222.pid

nohup ssh -p 2222 -N -R 8080:localhost:18080 admin@localhost >/tmp/ssh-1.log 2>&1 &

echo $! >/tmp/ssh-1.pid

nohup kubectl port-forward svc/dcloud-bastion-ingress-$1 8080:80 >/tmp/port-forward-2223.log 3>&1 &

echo $! >/tmp/port-forward-2223.pid

echo "Dcloud started, press ctrl+c to quite"

sleep 86400 # 60 * 60 * 24

kill $(cat /tmp/port-forward-2222.pid) $(cat /tmp/port-forward-2223.pid) $(cat /tmp/ssh-1.pid)

rm /tmp/port-forward-2222.pid /tmp/port-forward-2223.pid /tmp/ssh-1.pid /tmp/port-forward-2222.log /tmp/ssh-1.log /tmp/port-forward-2223.log
