import os
import sys
import re

# example: b (see demo)
istio_service_name = sys.argv[1]

if istio_service_name is None:
    raise RuntimeError("No service path")

USER_EMAIL = os.getenv('DCLOUD_USER_EMAIL')

PATH = 'deployment/kubernetes/dcloud/balancer'

if USER_EMAIL is None is None:
    raise RuntimeError("No local variables DCLOUD_USER_EMAIL found")

normalized_username = USER_EMAIL.split("@")[0]
matches = re.findall("[a-zA-Z]", normalized_username)
username = ''.join(matches)

files = os.listdir(PATH)
tmpl_files = [file for file in files if file.endswith('.tmpl')]

os.makedirs(f'{PATH}/autogenerated', exist_ok=True)

for file in tmpl_files:
    with open(f"{PATH}/{file}") as f:
        template = f.read()
        template = template.replace('$DCLOUD_USER_EMAIL', USER_EMAIL)
        template = template.replace('$DCLOUD_USER', username)
        template = template.replace('$DCLOUD_ISTIO_SERVICE_NAME', istio_service_name)

        file_yml = file.replace("tmpl", 'yml')
        with open(f'{PATH}/autogenerated/{file_yml}', 'w') as f:
            f.write(template)
cwd = os.getcwd()
os.system(f'{cwd}/scripts/register_cmd.sh {istio_service_name}')
