apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "b"
  labels:
    app: "b"
spec:
  selector:
    matchLabels:
      app: "b"
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: "b"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - imagePullPolicy: "IfNotPresent"
          image: "ealen/echo-server"
          ports:
            - name: "http"
              containerPort: 8080
          name: "b"
          env:
            - name: PORT
              value: "8080"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: "RollingUpdate"
